version: '2'
services:
  happy-mypet:
    image: ${DOCKER_REGISTRY_HOST}/happy-mypet:latest
    mem_limit: 1500m
    mem_reservation: 512m
    ports:
      - "0:9460"
    logging:
      driver: awslogs
      options:
        awslogs-group: happy-mypet
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: petclinic