spring:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9460

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  metrics:
    export:
      cloudwatch:
        namespace: m3trics2
        batchSize: 20

cloud:
  aws:
    region:
      static: ap-northeast-1

logging:
  level:
    ROOT: info
    io.micrometer: debug


