management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  metrics:
    export:
      cloudwatch:
        namespace: happy-mypet-local1
        batchSize: 20
      influx:
        uri: http://localhost:8086
        db: services
        step: 5s

logging:
  level:
    ROOT: info
    io.micrometer: debug


