management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  metrics:
    export:
      cloudwatch:
        namespace: happy-mypet-micrometer
        batchSize: 20
      influx:
        enabled: false

logging:
  level:
    ROOT: info

amazon:
  cloudwatch:
    metric:
      namespace: happy-mypet-awssdk


